#!/bin/bash

echo "🚀 Deploying Blue and Green versions..."
kubectl apply -f blue_deployment.yaml
kubectl apply -f green_deployment.yaml
kubectl apply -f kubeservice.yaml

echo "🔍 Checking logs for Green deployment..."
green_pods=$(kubectl get pods -l app=messaging-app,version=green -o jsonpath="{.items[*].metadata.name}")

for pod in $green_pods; do
  echo "📦 Logs for pod: $pod"
  kubectl logs "$pod"
done
